// Code generated by GoGamePlug DO NOT EDIT.

package R

var (
	MAP     = newMap_apzozj29sej5pxwx()
	RAW     = newRaw_5d3q2fd79x8dvhxz()
	AUDIO   = newAudio_x5g5qb9nwtodl6vx()
	IMAGE   = newImage_lj4h6238xlmq77oh()
	SHADER  = newShader_06h2qbt53q1b0kep()
	SPRITE  = newSprite_odm7q4oujj82dnlb()
	TILESET = newTileset_1ubwr3oyqfcqskrj()
	CLASS   = newClass_wz321rumchn99pea()
	LAYER   = newLayer_puxhxzo4ymp9s30p()
	OBJECT  = newObject_0kt4d3qanmu3m6of()
	PROP    = newProp_7i1lobu50b6pbuhb()
	MAIN    = newMain_ty2fa8x0l6jp1m7j()
)

type map_apzozj29sej5pxwx struct {
	MAIN string
}

func newMap_apzozj29sej5pxwx() *map_apzozj29sej5pxwx {
	return &map_apzozj29sej5pxwx{MAIN: "res/map/main.tmx"}
}

type raw_5d3q2fd79x8dvhxz struct {
	IPIX string
}

func newRaw_5d3q2fd79x8dvhxz() *raw_5d3q2fd79x8dvhxz {
	return &raw_5d3q2fd79x8dvhxz{IPIX: "res/raw/ipix.ttf"}
}

type audio_x5g5qb9nwtodl6vx struct {
}

func newAudio_x5g5qb9nwtodl6vx() *audio_x5g5qb9nwtodl6vx {
	return &audio_x5g5qb9nwtodl6vx{}
}

type image_lj4h6238xlmq77oh struct {
	MAIN string
}

func newImage_lj4h6238xlmq77oh() *image_lj4h6238xlmq77oh {
	return &image_lj4h6238xlmq77oh{MAIN: "res/image/main.png"}
}

type shader_06h2qbt53q1b0kep struct {
}

func newShader_06h2qbt53q1b0kep() *shader_06h2qbt53q1b0kep {
	return &shader_06h2qbt53q1b0kep{}
}

type sprite_odm7q4oujj82dnlb struct {
	MAIN string
}

func newSprite_odm7q4oujj82dnlb() *sprite_odm7q4oujj82dnlb {
	return &sprite_odm7q4oujj82dnlb{MAIN: "res/sprite/main.json"}
}

type tileset_1ubwr3oyqfcqskrj struct {
}

func newTileset_1ubwr3oyqfcqskrj() *tileset_1ubwr3oyqfcqskrj {
	return &tileset_1ubwr3oyqfcqskrj{}
}

type class_wz321rumchn99pea struct {
	CURSOR    string
	GRID      string
	CARD_SHOW string
	TIP       string
	UI_INFO   string
}

func newClass_wz321rumchn99pea() *class_wz321rumchn99pea {
	return &class_wz321rumchn99pea{CURSOR: "cursor", GRID: "grid", CARD_SHOW: "card_show", TIP: "tip", UI_INFO: "ui_info"}
}

type layer_puxhxzo4ymp9s30p struct {
	UI     string
	ENEMY  string
	PLAYER string
}

func newLayer_puxhxzo4ymp9s30p() *layer_puxhxzo4ymp9s30p {
	return &layer_puxhxzo4ymp9s30p{UI: "ui", ENEMY: "enemy", PLAYER: "player"}
}

type object_0kt4d3qanmu3m6of struct {
	CURSOR    string
	PATH      string
	CARD_SHOW string
	TIP       string
	UI_INFO   string
}

func newObject_0kt4d3qanmu3m6of() *object_0kt4d3qanmu3m6of {
	return &object_0kt4d3qanmu3m6of{CURSOR: "cursor", PATH: "path", CARD_SHOW: "card_show", TIP: "tip", UI_INFO: "ui_info"}
}

type prop_7i1lobu50b6pbuhb struct {
	PLACE string
}

func newProp_7i1lobu50b6pbuhb() *prop_7i1lobu50b6pbuhb {
	return &prop_7i1lobu50b6pbuhb{PLACE: "place"}
}

type main_ty2fa8x0l6jp1m7j struct {
	ENEMY  *enemy_hk7quuz2saew99tq
	PLAYER *player_6ypik4tlqc5ly38h
}

func newMain_ty2fa8x0l6jp1m7j() *main_ty2fa8x0l6jp1m7j {
	return &main_ty2fa8x0l6jp1m7j{ENEMY: newEnemy_hk7quuz2saew99tq(), PLAYER: newPlayer_6ypik4tlqc5ly38h()}
}

type enemy_hk7quuz2saew99tq struct {
	ENEMY1 string
	ENEMY2 string
	ENEMY3 string
	ENEMY4 string
	ENEMY5 string
	ENEMY6 string
	ENEMY7 string
	ENEMY8 string
}

func newEnemy_hk7quuz2saew99tq() *enemy_hk7quuz2saew99tq {
	return &enemy_hk7quuz2saew99tq{ENEMY1: "enemy/enemy1", ENEMY2: "enemy/enemy2", ENEMY3: "enemy/enemy3", ENEMY4: "enemy/enemy4", ENEMY5: "enemy/enemy5", ENEMY6: "enemy/enemy6", ENEMY7: "enemy/enemy7", ENEMY8: "enemy/enemy8"}
}

type player_6ypik4tlqc5ly38h struct {
	PLAYER1  string
	PLAYER10 string
	PLAYER11 string
	PLAYER12 string
	PLAYER2  string
	PLAYER3  string
	PLAYER4  string
	PLAYER5  string
	PLAYER6  string
	PLAYER7  string
	PLAYER8  string
	PLAYER9  string
}

func newPlayer_6ypik4tlqc5ly38h() *player_6ypik4tlqc5ly38h {
	return &player_6ypik4tlqc5ly38h{PLAYER1: "player/player1", PLAYER10: "player/player10", PLAYER11: "player/player11", PLAYER12: "player/player12", PLAYER2: "player/player2", PLAYER3: "player/player3", PLAYER4: "player/player4", PLAYER5: "player/player5", PLAYER6: "player/player6", PLAYER7: "player/player7", PLAYER8: "player/player8", PLAYER9: "player/player9"}
}
